#!/bin/bash

__usage() {

  # pipe `stdout` to `stderr`
  echo "Usage: $0 [-i input_dir] [-I input_ext] [-o output_dir] [-O output_ext] -- run_cmd" 1>&2

}

__error() {

  # pipe `stdout` to `stderr`
  echo "$0: $1" 1>&2

  # print usage message if $2 is set
  if [ -n "$2" ]; then
    __usage
  fi

  # exit with code 1
  exit 1

}

__normalise_dir() {

  # set to the default if unset
  local dir=${1:-"$2"}

  # strip the trailing '/'
  printf "${dir%/}"

}

__normalise_ext() {

  # set to the default if unset
  if [ -z "$1" ]; then
    printf ""
  else
    printf ".${1#.}"
  fi

}

__not_ok() {

  local msg="$3"
  printf "not ok $1 - $2\n  ---\n  error: "

  # check if $msg spans multiple lines
  if [ $(echo "$msg" | wc -l) -gt 1 ]; then
    msg=${msg/	/  }
    msg=${msg/
/
    }
    echo "|\n    $msg";
  else
    echo "'$msg'"
  fi
  echo "  ..."

}

__str_starts_with() {

  case "$1" in
    "$2"*) echo 1;;
    *) echo;;
  esac

}

# parse command line arguments
while [ "$#" -gt 0 ]; do

  # if $run_cmd is still unset
  if [ -z "$run_cmd" ]; then

    case "$1" in
      # flag options with value
      -i | -I | -o | -O | -a)
        # check that a value was specified after the flag
        if [ -z "$2" ] || [ -n "$(__str_starts_with $2 '-')" ]; then
          __error "$1: option expects a value"
        fi
        case "$1" in
          -i) input_dir="$2";;
          -I) input_ext="$2";;
          -o) output_dir="$2";;
          -O) output_ext="$2";;
          -a) actual_dir="$2";;
        esac
        shift
        ;;
      # non-flag options
      *)
        if [ "$1" == "--" ]; then
          if [ -z "$2" ]; then
            __error "need a run command" 1
          fi
          run_cmd="$2"
          shift
        else
          run_cmd="$1"
        fi
        ;;
    esac

  else
    run_cmd="$run_cmd $1"
  fi

  shift

done

# fail if no run command
if [ -z "$run_cmd" ]; then
  __error "need a run command" 1
fi

# normalise options
input_dir=$(__normalise_dir "$input_dir" "input")
input_ext=$(__normalise_ext "$input_ext")
output_dir=$(__normalise_dir "$output_dir" "output")
output_ext=$(__normalise_ext "$output_ext")
actual_dir=$(__normalise_dir "$actual_dir" "actual")

# fail if $input_dir or $output_dir not found
if [ ! -d "$input_dir" ]; then
  __error "$input_dir: no such input directory"
fi
if [ ! -d "$output_dir" ]; then
  __error "$output_dir: no such output directory"
fi

# empty $actual_dir
rm -rf "$actual_dir"
mkdir -p "$actual_dir"

# store input file names in $input_files
num_tests=0
for input_file in "$input_dir"/*"$input_ext"; do

  # only include files
  if [ -f "$input_file" ]; then
    input_files["$num_tests"]="$input_file"
    ((num_tests++))
  fi

done

# fail if no input files in $input_dir
if [ "$num_tests" -eq 0 ]; then
  __error "$input_dir: no input files found"
fi

# print TAP version and plan
echo "TAP version 13"

# count passing tests
num_pass=0

# counter for numbering tests
i=1

# iterate over input file names in the $input_files array
for input_file in "${input_files[@]}"; do

  # resolve $input_basename and $test_name
  input_basename=$(basename "$input_file")
  test_name=${input_basename%.*}

  # resolve $output_file and $actual_file
  if [ -n "$output_ext" ]; then
    output_basename="$test_name""$output_ext"
  else
    output_basename="$input_basename"
  fi
  output_file="$output_dir"/"$output_basename"
  actual_file="$actual_dir"/"$output_basename"

  # redirect `stderr` to `stdout`, and `stdout` to $actual_file
  err=$(eval "$run_cmd" < "$input_file" 2>&1 >| "$actual_file")

  # check if $err is empty
  if [ -z "$err" ]; then

    # check if $output_file exists
    if [ -f "$output_file" ]; then

      # compare expected output with actual output
      cmp_result=$(cmp "$output_file" "$actual_file" 2>&1)

      # check if $cmp_result is empty
      if [ -z "$cmp_result" ]; then
        echo "ok $i - $test_name"
        ((num_pass++))
      else
        __not_ok "$i" "$test_name" "$cmp_result"
      fi

    else
      __not_ok "$i" "$test_name" "$output_file: no such file"
    fi

  else
    __not_ok "$i" "$test_name" "$err"
  fi

  # increment counter
  ((i++))

done

# count failing tests
num_fail=$((num_tests - num_pass))

# print result summary
echo "# tests $num_tests"
echo "# pass  $num_pass"
echo "# fail  $num_fail"

# exit with code 1 if some tests failed
if [ "$num_fail" -ne 0 ]; then
  exit 1
fi
